# Generated by Django 4.0.3 on 2022-03-12 20:51

from django.db import migrations, models
import multiselectfield.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Race",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "race_uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("tiny", "tiny"),
                            ("small", "small"),
                            ("medium", "medium"),
                            ("large", "large"),
                            ("huge", "huge"),
                            ("gargantuan", "gargantuan"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("speed", models.PositiveIntegerField(default=30)),
                ("strength_ability_increase", models.PositiveIntegerField(default=0)),
                ("dexterity_ability_increase", models.PositiveIntegerField(default=0)),
                (
                    "constitution_ability_increase",
                    models.PositiveIntegerField(default=0),
                ),
                (
                    "intelligince_ability_increase",
                    models.PositiveIntegerField(default=0),
                ),
                ("wisdom_ability_increase", models.PositiveIntegerField(default=0)),
                ("charisma_ability_increase", models.PositiveIntegerField(default=0)),
                (
                    "additional_ability_increases",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="For every additional +1 to stat attribute increase this value by 1. (example: Half Elf gets 2 addional stat increase by 1, so this value would be 2.)",
                    ),
                ),
                (
                    "languages",
                    multiselectfield.db.fields.MultiSelectField(
                        blank=True,
                        choices=[
                            ("common", "common"),
                            ("dwarvish", "dwarvish"),
                            ("elvish", "elvish"),
                            ("giant", "giant"),
                            ("gnomish", "gnomish"),
                            ("goblin", "goblin"),
                            ("halfling", "halfling"),
                            ("orc", "orc"),
                            ("abyssal", "abyssal"),
                            ("celestial", "celestial"),
                            ("deep speech", "deep speech"),
                            ("infernal", "infernal"),
                            ("primordial", "primordial"),
                            ("sylvan", "sylvan"),
                            ("draconic", "draconic"),
                            ("undercommon", "undercommon"),
                        ],
                        max_length=134,
                        null=True,
                    ),
                ),
            ],
        ),
    ]
