# Generated by Django 4.0.3 on 2022-03-12 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("races", "0002_alter_race_languages"),
    ]

    operations = [
        migrations.AddField(
            model_name="race",
            name="additional_ability_increases",
            field=models.PositiveIntegerField(
                default=0,
                help_text="For every additional +1 to stat attribute increase this value by 1. (example: Half Elf gets 1 addional stat increase by 1, so this value would be 1. Where as Human Variant gets to increase 2 stats by 1 point each, so this value would be 2.)",
            ),
        ),
    ]
