# Generated by Django 4.0.3 on 2022-03-12 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0003_race_additional_ability_increases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='additional_ability_increases',
            field=models.PositiveIntegerField(default=0, help_text='For every additional +1 to stat attribute increase this value by 1. (example: Half Elf gets 2 addional stat increase by 1, so this value would be 2.)'),
        ),
    ]
