# Generated by Django 4.0.3 on 2022-03-12 23:39

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('races', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_stat_preference', models.CharField(choices=[('random', 'random'), ('race_weighted_perferred', 'race_weighted_perferred'), ('race_weighted_balanced', 'race_weighted_balanced'), ('class_weighted_perferred', 'class_weighted_perferred')], default='random', max_length=24)),
                ('other_attribute_increases', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('strength', 'strength'), ('dexterity', 'dexterity'), ('constitution', 'constitution'), ('intelligence', 'intelligence'), ('wisdom', 'wisdom'), ('charisma', 'charisma')], max_length=60, null=True)),
                ('character_uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=120)),
                ('age', models.PositiveIntegerField(default=22)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=6)),
                ('background', models.TextField(blank=True)),
                ('base_strength', models.PositiveIntegerField(default=0, editable=False)),
                ('base_dexterity', models.PositiveIntegerField(default=0, editable=False)),
                ('base_constitution', models.PositiveIntegerField(default=0, editable=False)),
                ('base_intelligence', models.PositiveIntegerField(default=0, editable=False)),
                ('base_wisdom', models.PositiveIntegerField(default=0, editable=False)),
                ('base_charisma', models.PositiveIntegerField(default=0, editable=False)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='races.race')),
            ],
        ),
    ]
