# Generated by Django 4.0.3 on 2022-03-12 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="age",
            field=models.PositiveIntegerField(default=11),
        ),
    ]
