# Generated by Django 4.0.3 on 2022-03-13 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character_classes', '0001_initial'),
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='character_class',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='character_classes.characterclass'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='experience',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='level',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='character',
            name='age',
            field=models.PositiveIntegerField(default=21),
        ),
        migrations.AlterField(
            model_name='character',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], default='female', max_length=6),
        ),
    ]
