# Generated by Django 4.0.3 on 2022-03-09 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_alter_character_base_charisma_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='base_charisma',
            field=models.PositiveIntegerField(default=17, editable=False),
        ),
        migrations.AlterField(
            model_name='character',
            name='base_constitution',
            field=models.PositiveIntegerField(default=16, editable=False),
        ),
        migrations.AlterField(
            model_name='character',
            name='base_dexterity',
            field=models.PositiveIntegerField(default=15, editable=False),
        ),
        migrations.AlterField(
            model_name='character',
            name='base_wisdom',
            field=models.PositiveIntegerField(default=7, editable=False),
        ),
    ]
