# Generated by Django 4.0.3 on 2022-03-12 20:57

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0003_alter_character_age_alter_character_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="age",
            field=models.PositiveIntegerField(default=12),
        ),
        migrations.AlterField(
            model_name="character",
            name="gender",
            field=models.CharField(
                choices=[("male", "male"), ("female", "female")],
                default="male",
                max_length=6,
            ),
        ),
        migrations.AlterField(
            model_name="character",
            name="other_attribute_increases",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("strength", "strength"),
                    ("dexterity", "dexterity"),
                    ("constitution", "constitution"),
                    ("intelligence", "intelligence"),
                    ("wisdom", "wisdom"),
                    ("charisma", "charisma"),
                ],
                max_length=60,
                null=True,
            ),
        ),
    ]
