# Generated by Django 4.0.3 on 2022-03-13 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_alter_character_character_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='max_hp',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='age',
            field=models.PositiveIntegerField(default=25),
        ),
        migrations.AlterField(
            model_name='character',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=6),
        ),
    ]
