# Generated by Django 4.0.3 on 2022-03-14 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0004_character_max_hp_alter_character_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='age',
            field=models.PositiveIntegerField(default=17),
        ),
    ]
