# Generated by Django 4.0.3 on 2022-03-12 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0005_alter_character_age"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="age",
            field=models.PositiveIntegerField(default=26),
        ),
    ]
