# Generated by Django 4.0.3 on 2022-03-07 04:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0007_alter_character_base_charisma_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="race",
            field=models.CharField(
                blank=True,
                choices=[(uuid.UUID("84dfa520-de3b-4423-ae6b-ca8c7deff39c"), "Dwarf")],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="character",
            name="base_charisma",
            field=models.PositiveIntegerField(default=18, editable=False),
        ),
        migrations.AlterField(
            model_name="character",
            name="base_constitution",
            field=models.PositiveIntegerField(default=14, editable=False),
        ),
        migrations.AlterField(
            model_name="character",
            name="base_intelligence",
            field=models.PositiveIntegerField(default=13, editable=False),
        ),
        migrations.AlterField(
            model_name="character",
            name="base_strength",
            field=models.PositiveIntegerField(default=6, editable=False),
        ),
        migrations.AlterField(
            model_name="character",
            name="base_wisdom",
            field=models.PositiveIntegerField(default=11, editable=False),
        ),
    ]
