# Generated by Django 4.0.3 on 2022-03-07 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("race", "0004_race_charisma_ability_increase_and_more"),
        ("characters", "0017_alter_character_base_charisma_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="base_charisma",
            field=models.PositiveIntegerField(default=11, editable=False),
        ),
        migrations.AlterField(
            model_name="character",
            name="base_constitution",
            field=models.PositiveIntegerField(default=11, editable=False),
        ),
        migrations.AlterField(
            model_name="character",
            name="base_dexterity",
            field=models.PositiveIntegerField(default=10, editable=False),
        ),
        migrations.AlterField(
            model_name="character",
            name="base_intelligence",
            field=models.PositiveIntegerField(default=12, editable=False),
        ),
        migrations.AlterField(
            model_name="character",
            name="base_strength",
            field=models.PositiveIntegerField(default=8, editable=False),
        ),
        migrations.AlterField(
            model_name="character",
            name="base_wisdom",
            field=models.PositiveIntegerField(default=13, editable=False),
        ),
        migrations.RemoveField(
            model_name="character",
            name="race",
        ),
        migrations.AddField(
            model_name="character",
            name="race",
            field=models.ManyToManyField(
                blank=True, default=None, null=True, related_name="race", to="race.race"
            ),
        ),
    ]
