# Generated by Django 4.0.3 on 2022-03-07 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("race", "0004_race_charisma_ability_increase_and_more"),
        ("characters", "0018_alter_character_base_charisma_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="character",
            name="race",
        ),
        migrations.AddField(
            model_name="character",
            name="races",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                null=True,
                related_name="races",
                to="race.race",
            ),
        ),
        migrations.AlterField(
            model_name="character",
            name="base_charisma",
            field=models.PositiveIntegerField(default=13, editable=False),
        ),
        migrations.AlterField(
            model_name="character",
            name="base_constitution",
            field=models.PositiveIntegerField(default=16, editable=False),
        ),
        migrations.AlterField(
            model_name="character",
            name="base_dexterity",
            field=models.PositiveIntegerField(default=13, editable=False),
        ),
        migrations.AlterField(
            model_name="character",
            name="base_intelligence",
            field=models.PositiveIntegerField(default=6, editable=False),
        ),
        migrations.AlterField(
            model_name="character",
            name="base_strength",
            field=models.PositiveIntegerField(default=13, editable=False),
        ),
        migrations.AlterField(
            model_name="character",
            name="base_wisdom",
            field=models.PositiveIntegerField(default=16, editable=False),
        ),
    ]
