# Generated by Django 4.0.3 on 2022-03-07 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0021_remove_character_races_character_race_uuid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="race_type",
            field=models.CharField(
                choices=[
                    ("Mountain Dwarf", "Mountain Dwarf"),
                    ("Dwarf", "Dwarf"),
                    ("Hill dwarf", "Hill dwarf"),
                    ("Wood Elf", "Wood Elf"),
                    ("High Elf", "High Elf"),
                    ("Elf", "Elf"),
                    ("Dark Elf", "Dark Elf"),
                ],
                default="male",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="character",
            name="base_charisma",
            field=models.PositiveIntegerField(default=16, editable=False),
        ),
        migrations.AlterField(
            model_name="character",
            name="base_constitution",
            field=models.PositiveIntegerField(default=11, editable=False),
        ),
        migrations.AlterField(
            model_name="character",
            name="base_dexterity",
            field=models.PositiveIntegerField(default=11, editable=False),
        ),
        migrations.AlterField(
            model_name="character",
            name="base_intelligence",
            field=models.PositiveIntegerField(default=13, editable=False),
        ),
        migrations.AlterField(
            model_name="character",
            name="base_strength",
            field=models.PositiveIntegerField(default=8, editable=False),
        ),
        migrations.AlterField(
            model_name="character",
            name="base_wisdom",
            field=models.PositiveIntegerField(default=16, editable=False),
        ),
    ]
