# Generated by Django 4.0.3 on 2022-03-07 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "characters",
            "0022_character_race_type_alter_character_base_charisma_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="character",
            name="race_type",
        ),
        migrations.AlterField(
            model_name="character",
            name="base_charisma",
            field=models.PositiveIntegerField(default=17, editable=False),
        ),
        migrations.AlterField(
            model_name="character",
            name="base_constitution",
            field=models.PositiveIntegerField(default=16, editable=False),
        ),
        migrations.AlterField(
            model_name="character",
            name="base_dexterity",
            field=models.PositiveIntegerField(default=10, editable=False),
        ),
        migrations.AlterField(
            model_name="character",
            name="base_intelligence",
            field=models.PositiveIntegerField(default=12, editable=False),
        ),
        migrations.AlterField(
            model_name="character",
            name="base_wisdom",
            field=models.PositiveIntegerField(default=10, editable=False),
        ),
    ]
