# Generated by Django 4.0.3 on 2022-03-07 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("race", "0004_race_charisma_ability_increase_and_more"),
        ("characters", "0023_remove_character_race_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="race_type",
            field=models.CharField(
                choices=[
                    ("Mountain Dwarf", "Mountain Dwarf"),
                    ("Dwarf", "Dwarf"),
                    ("Hill dwarf", "Hill dwarf"),
                    ("Wood Elf", "Wood Elf"),
                    ("High Elf", "High Elf"),
                    ("Elf", "Elf"),
                    ("Dark Elf", "Dark Elf"),
                ],
                default="male",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="character",
            name="base_charisma",
            field=models.PositiveIntegerField(default=11, editable=False),
        ),
        migrations.AlterField(
            model_name="character",
            name="base_constitution",
            field=models.PositiveIntegerField(default=12, editable=False),
        ),
        migrations.AlterField(
            model_name="character",
            name="base_dexterity",
            field=models.PositiveIntegerField(default=8, editable=False),
        ),
        migrations.AlterField(
            model_name="character",
            name="base_strength",
            field=models.PositiveIntegerField(default=12, editable=False),
        ),
        migrations.AlterField(
            model_name="character",
            name="race_uuid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="race.race"
            ),
        ),
    ]
