# Generated by Django 4.0.3 on 2022-03-07 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "characters",
            "0024_character_race_type_alter_character_base_charisma_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="character",
            old_name="race_uuid",
            new_name="race",
        ),
        migrations.AlterField(
            model_name="character",
            name="base_charisma",
            field=models.PositiveIntegerField(default=14, editable=False),
        ),
        migrations.AlterField(
            model_name="character",
            name="base_constitution",
            field=models.PositiveIntegerField(default=15, editable=False),
        ),
        migrations.AlterField(
            model_name="character",
            name="base_dexterity",
            field=models.PositiveIntegerField(default=18, editable=False),
        ),
        migrations.AlterField(
            model_name="character",
            name="base_intelligence",
            field=models.PositiveIntegerField(default=9, editable=False),
        ),
        migrations.AlterField(
            model_name="character",
            name="base_strength",
            field=models.PositiveIntegerField(default=14, editable=False),
        ),
        migrations.AlterField(
            model_name="character",
            name="base_wisdom",
            field=models.PositiveIntegerField(default=11, editable=False),
        ),
    ]
