# Generated by Django 4.0.3 on 2022-03-07 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0025_rename_race_uuid_character_race_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="character",
            name="race_type",
        ),
        migrations.AlterField(
            model_name="character",
            name="base_charisma",
            field=models.PositiveIntegerField(default=10, editable=False),
        ),
        migrations.AlterField(
            model_name="character",
            name="base_constitution",
            field=models.PositiveIntegerField(default=11, editable=False),
        ),
        migrations.AlterField(
            model_name="character",
            name="base_dexterity",
            field=models.PositiveIntegerField(default=12, editable=False),
        ),
        migrations.AlterField(
            model_name="character",
            name="base_intelligence",
            field=models.PositiveIntegerField(default=8, editable=False),
        ),
        migrations.AlterField(
            model_name="character",
            name="base_strength",
            field=models.PositiveIntegerField(default=8, editable=False),
        ),
        migrations.AlterField(
            model_name="character",
            name="base_wisdom",
            field=models.PositiveIntegerField(default=13, editable=False),
        ),
    ]
