# Generated by Django 4.0.3 on 2022-03-12 23:39

from django.db import migrations, models
import multiselectfield.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterClass',
            fields=[
                ('character_class_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('hit_die', models.CharField(choices=[('d4', 'd4'), ('d6', 'd6'), ('d8', 'd8'), ('d10', 'd10'), ('d12', 'd12'), ('d20', 'd20')], default='d8', max_length=3)),
                ('primary_abilities', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('strength', 'strength'), ('dexterity', 'dexterity'), ('constitution', 'constitution'), ('intelligence', 'intelligence'), ('wisdom', 'wisdom'), ('charisma', 'charisma')], max_length=60, null=True)),
                ('saving_thow_proficiencies', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('strength', 'strength'), ('dexterity', 'dexterity'), ('constitution', 'constitution'), ('intelligence', 'intelligence'), ('wisdom', 'wisdom'), ('charisma', 'charisma')], max_length=60, null=True)),
            ],
        ),
    ]
