# Generated by Django 4.0.3 on 2022-03-08 18:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(default='Dwarf', max_length=120)),
                ('description', models.TextField(blank=True)),
                ('size', models.CharField(choices=[('tiny', 'tiny'), ('small', 'small'), ('medium', 'medium'), ('large', 'large'), ('huge', 'huge'), ('gargantuan', 'gargantuan')], default='medium', max_length=10)),
                ('speed', models.PositiveIntegerField(default=30)),
                ('strength_ability_increase', models.PositiveIntegerField(default=0)),
                ('dexterity_ability_increase', models.PositiveIntegerField(default=0)),
                ('constitution_ability_increase', models.PositiveIntegerField(default=0)),
                ('intellegince_ability_increase', models.PositiveIntegerField(default=0)),
                ('wisdom_ability_increase', models.PositiveIntegerField(default=0)),
                ('charisma_ability_increase', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
