# Generated by Django 4.0.3 on 2022-03-07 02:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Race",
            fields=[
                (
                    "race_uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(default="Dwarf", max_length=120)),
                ("description", models.TextField(blank=True)),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("tiny", "tiny"),
                            ("small", "small"),
                            ("medium", "medium"),
                            ("large", "large"),
                            ("huge", "huge"),
                            ("gargantuan", "gargantuan"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("speed", models.PositiveIntegerField(default=30)),
            ],
        ),
    ]
