# Generated by Django 4.0.3 on 2022-03-09 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
        ('race', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='languages',
            field=models.ManyToManyField(blank=True, to='languages.language'),
        ),
    ]
