# Generated by Django 4.0.3 on 2022-03-07 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("race", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="race",
            name="sub_class",
            field=models.CharField(
                blank=True,
                choices=[
                    ("hill dwarf", "hill dwarf"),
                    ("mountain dwarf", "mountain dwarf"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
