# Generated by Django 4.0.3 on 2022-03-07 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("race", "0002_race_sub_class"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="race",
            name="sub_class",
        ),
    ]
