# Generated by Django 4.0.3 on 2022-03-09 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0002_alter_language_language_uuid'),
        ('race', '0003_alter_race_race_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='race',
            name='languages',
        ),
        migrations.AddField(
            model_name='race',
            name='languages',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='language_uuid+', to='languages.language'),
            preserve_default=False,
        ),
    ]
