# Generated by Django 4.0.3 on 2022-03-09 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0003_remove_language_id_alter_language_language_uuid'),
        ('race', '0007_alter_race_languages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='race',
            name='languages',
        ),
        migrations.AddField(
            model_name='race',
            name='languages',
            field=models.ManyToManyField(blank=True, to='languages.language'),
        ),
    ]
