# Generated by Django 4.0.3 on 2022-03-09 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('race', '0008_remove_race_languages_race_languages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='race',
            old_name='languages',
            new_name='language_uuids',
        ),
    ]
